.github/workflows/main.yml

To ensure that any contributions are consistent and proper, add a GitHub
Action that runs shellcheck on any scripts.
For an example of how an error manifests and gets reported:
https://github.com/nathanchance/boot-utils/actions/runs/68702038

github: Add Actions workflow

---

boot-qemu.sh

An upcoming QEMU change will make it so that the bmc devices are created
automatically. Unfortunately, that breaks our command line with the
following cryptic error:
qemu-system-ppc64: error creating device tree: node: FDT_ERR_EXISTS
The author of the patch changed it so that the devices are only created
when '-nodefaults' is not set (i.e. using defaults). Add this flag to
our QEMU command line so that this command line continues to work for
all QEMU versions. Tested locally with 3.1.0 (the version in Debian
stable), 4.2.0 (current QEMU stable), and 5.0.0-rc1 (latest QEMU -rc).
Link: https://lore.kernel.org/qemu-devel/20200404071707.GA24708@ubuntu-m2-xlarge-x86/
Link: https://lore.kernel.org/qemu-devel/20200404153655.166834-1-clg@kaod.org/

boot-qemu.sh: Add '-nodefaults' to ppc64le command line

---

boot-qemu.sh

This prevents QEMU from creating devices underneath us, which can change
across QEMU versions (see de875be20ca66). To prevent this in the future,
add '-nodefaults' for all invocations of QEMU, not just powerpc64le.
Tested with QEMU 3.1.0, 4.2.0, and 5.0.0-rc2.
NOTE: This is the only architecture that we actually set devices for so
this should be a no-op for everything else but we might add other
devices in the future.

boot-qemu.sh: Hoist '-nodefaults' from ppc64le arguments to main arguments

---

boot-qemu-help.txt
boot-qemu.sh

Adding '-s -S' stops the CPU and allows us to connect with GDB via
'target remote :1234'.
This implies '-i' so that the machine does not get killed in the middle
of debugging.

boot-qemu.sh: Add the ability to debug with GDB

---

boot-qemu.sh

We might not want this for cases where you do want to see dmesg output,
but you can always run lx-dmesg in gdb.
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>

autolaunch gdb

---

.github/workflows/main.yml
boot-qemu.sh
buildroot/rebuild.sh

Uses [mvdan/sh](https://github.com/mvdan/sh) to enable formatting checks in CI, and correctly fails when the codestyle is [incorrect](https://github.com/msfjarvis/boot-utils/actions/runs/85612538), outputting a diff with fixes.
I chose the set of options that made the most sense to me, all available switches are listed [here](https://bin.msfjarvis.dev/~5ea167531de3ad00122e4ec0).

Reformat shell scripts with shfmt and validate in CI

---

.github/CODEOWNERS
README.txt
boot-qemu.sh

Commits are pretty self explanatory :)
@msfjarvis @tpimh are you guys okay being code owners for this repo?

A few small fixups

---

boot-qemu.sh

The x86 section unconditionally adds -enable-kvm to the QEMU flags. This
won't work for Travis because it does not have KVM support. The x86_64
section handles this already and the only difference between the x86 and
x86_64 sections is the QEMU binary name. Combine the sections and handle
that so that there is less duplication and everything works properly.

boot-qemu.sh: Combine x86 and x86_64 for shared KVM handling

---

boot-qemu.sh

I was pulling my hair out trying to debug
https://github.com/ClangBuiltLinux/linux/issues/852 since breakpoints I
set were never hit.
Sami Tolvanen (@samitolvanen) reminded me I need to disable KASLR via
nokaslr kernel command line parameter.
Separate out the -append string from QEMU_ARCH_ARGS, since we need to
change it both for interactive and debug mode.

disable KASLR when using GDB

---

boot-qemu.sh

When a kernel is hung, we currently have to wait the timeout to exit,
(or ctrl+z; `pkill timeout; fg`).  For complicated reasons, running timeout
from a shell script won't forward signals to timeout.
Adding --foreground is the simplest option for this to work, via:
https://unix.stackexchange.com/a/233685/388381
See other answers in that thread for *why* this is the case.

run timeout in the foreground so it can be killed

---

boot-qemu.sh

The unit tests enabled via CONFIG_KCSAN_TEST require >1 CPU to run.
Enable more cpu's via QEMU's `-smp <n>` command line flag.
Not sure if we should just do this for all ARCHs and if we should use a
value like 8 or min(nproc, 8).
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>

enable more virtual cores for x86

---

README.txt
boot-qemu.sh

Since `gdb` likely was only configured for the those triple.

gdb: require gdb-multiarch for -g

---

boot-qemu.sh

The PAC/BTI instructions were added in v8.3a/v8.5a.
(See https://reviews.llvm.org/D62609).
Without enabling this cpu, the instructions are treated as NOPS.  Switch
to a CPU that will use these instructions, testing kernel configs
(CONFIG_ARM64_PTR_AUTH, CONFIG_ARM64_BTI) which we will ship and
Android+CrOS as soon as hardware is available.
Suggested-by: Mark Brown <broonie@kernel.org>

qemu: aarch64: switch to -cpu max for PAC/BTI

---

boot-qemu.sh

zImage has always been a hardlink to uImage but as of a refactoring in
5.8-rc1, that is no longer guaranteed to be the case. Explicitly use the
uImage, which will always work for QEMU.
Link: https://lore.kernel.org/linuxppc-dev/87bllidmk4.fsf@mpe.ellerman.id.au/

boot-qemu.sh: Expect uImage for ppc32

---

README.txt
boot-qemu.sh

There are times where supplying a kernel image directly makes more sense
than providing the build output folder. For example, when using tuxmake,
the build output folder is automatically cleaned up, leaving just the
compiled artifacts. To boot kernels in this way, one would have to make
a fake boot folder and copy the image to it.
Convert '-k' to either take a kernel image directly or the kernel build
output folder.

boot-qemu.sh: Allow the user to supply a kernel image directly

---

boot-qemu.sh

The first commit has the full details in the commit message.
The second one is a small quality of life change that I noticed while debugging this.

Fix finding the dtb after the kernel image location refactoring

---

.gitignore
README.txt
boot-qemu.sh

We need to do this in order to boot s390 kernels in our CI. The qemu
binaries are hosted in a separate repo to keep things reasonable in
terms of file size.
This is part two in resolving https://github.com/ClangBuiltLinux/continuous-integration2/issues/42.

boot-utils: Add '--use-cbl-qemu'

---

README.txt
boot-qemu.sh

Part 2 of resolving https://github.com/ClangBuiltLinux/continuous-integration2/issues/72

boot-utils: Add RISC-V to use '--use-cbl-qemu'

---

README.txt
boot-qemu.sh

RISC-V no longer needs it.
Link: https://bugs.launchpad.net/bugs/1914883

boot-utils: Only allow '--use-cbl-qemu' with s390

---

boot-qemu.sh

There is currently a crash on -next for RISC-V that is not visible
without this. For all ARM architectures supported with this script, just
"earlycon" works because the device trees have support for the console
and baud rates. RISC-V is the same way. x86 needs the type of I/O and
address. ttyS0 is 0x3f8 (arch/x86/boot/early_serial_console.c) and we
do regular I/O. The baud rate works with the default so it is omitted.
MIPS already has earlycon enabled.
I cannot find any research on earlycon on PowerPC or s390 so they are
omitted.

boot-qemu.sh: Add support for earlycon

---

buildroot/overlay-poweroff/etc/init.d/S50yolo
buildroot/overlay-reboot/etc/init.d/S50yolo

Currently, when booting the images, the version string prints out twice.
This is because these scripts are called twice: once with the "start"
action and again with the "stop" action.
To avoid this, just run the contents of the script when the service is
starting.
Given that this is a purely cosmetic issue, I do not think that it is
worth rebuilding the images over.
Closes: #41

buildroot: Check init.d action to avoid double version print out

---

debian/build.sh

qemu-debootstrap has been deprecated in favor of just running
debootstrap due to the use of the "F" flag with binfmt_misc.
https://salsa.debian.org/qemu-team/qemu/-/commit/9899b1723119e57354c5d8e6f68f15ed762bd570
This makes it easier for other distributions to run the script because
debootstrap is usually available from the package manager but
qemu-debootstrap is a part of Debian's qemu-user-static package.

debian/build.sh: qemu-debootstrap -> debootstrap

---

boot-qemu.sh

Otherwise, the console changes midboot and we lose output, making it
look like a hang.

boot-qemu.sh: Do not set earlycon for arm32_v6

---

README.txt
boot-qemu.sh

There are times where reproducing a bug may require not using KVM. Add a
flag that allows the user to use QEMU's software emulation.

boot-qemu.sh: Add '--no-kvm' option

---

README.txt
boot-qemu.sh

The help text is fairly self explanatory.

boot-qemu.sh: Add '--smp' flag

---

boot-qemu.sh

To avoid needing the "expect" package, use "stdbuf" from coreutils to control output buffering. While at it, switch to line-buffering to avoid stdout/stderr mixing.

boot-qemu.sh: Use stdbuf instead of unbuffer

---

README.txt
boot-qemu.sh

This option was intended for CI usage, which has now moved to a
container based workflow, so that we can easily get access to newer QEMU
versions, which makes this option obsolete. Remove it.

boot-utils: Remove '--use-cbl-qemu'

---

README.txt
boot-qemu.sh

This is an opinionated change but one I think most people will agree
with. I boot test multi_v7_defconfig variants more than either of the
other 32-bit ARM configurations we test and remembering to put the
'32_v7' part is rather annoying. Add 'arm' as a valid '-a' value so that
it works the same as 'arm32_v7'.

boot-qemu.sh: Add 'arm' as an alias for 'arm32_v7'

---

README.txt
boot-qemu.sh

pmac32_defconfig can be booted using the mac99 machine in QEMU using the
same rootfs that we use for the bamboo machine.
pmac32_defconfig boots fine by itself but to get console output
properly, two configs need to be enabled:
```
CONFIG_SERIAL_PMACZILOG=y
CONFIG_SERIAL_PMACZILOG_CONSOLE=y
```

boot-qemu.sh: Add support for booting pmac32_defconfig

---

boot-qemu.sh

This causes warnings when using TCG (i.e. no KVM):
```
qemu-system-i386: warning: TCG doesn't support requested feature: CPUID.80000001H:EDX.syscall [bit 11]
qemu-system-i386: warning: TCG doesn't support requested feature: CPUID.80000001H:EDX.lm [bit 29]
```
The '-cpu' flag was added to support using prebuilt GCC toolchains in
Buildroot in commit 344ff00 ("boot-qemu.sh: Use Nehalem for non-KVM boot
on x86_64") but I forgot that this block applies to both 32-bit and
64-bit x86.
Given that Nehalem is a 64-bit microarchitecture, this flag should only
be supplied when booting an x86_64 kernel, which removes the warning for
`-a x86`.

boot-qemu.sh: Do not set '-cpu' for 32-bit x86

---

boot-qemu.sh

This series implements a heuristic for the default '-smp' value when KVM is used and uses '-smp' for arm and arm64 KVM for better performance.

Improve default '-smp' value

---

boot-qemu.sh

Starting with QEMU commit 69b2265d5fe8e, aarch64 kernels older than
5.12.0 do not boot without "lpa2=off". Add this parameter when booting a
kernel older than this version using a version of QEMU that has this
commit.
We cannot universally pass this for all QEMU versions because the
property is not recognized on older version:
qemu-system-aarch64: can't apply global max-arm-cpu.lpa2=off: Property 'max-arm-cpu.lpa2' not found
We could pass this for all kernel versions but we miss out on testing a
default QEMU change.
The first three commits add the individual functions that are needed by the
last commit for ease of reviewing.
Link: https://gitlab.com/qemu-project/qemu/-/commit/69b2265d5fe8e0f401d75e175e0a243a7d505e53

boot-qemu.sh: arm64: Pass 'lpa2=off' when necessary

---

boot-qemu.sh

After FEAT_LPA was implemented in QEMU's TCG, kernels older than 4.19,
namely 4.9 and 4.14, fail to boot. We already have a workaround for
FEAT_LPA2 not working with kernels older than 5.12, which is known.
Reporting this to QEMU upstream resulted in the recommendation to use
one of the ARMv8.0 CPUs for these older kernels. Use 'cortex-a72' for
booting anything older than 4.19 with QEMU 6.2.50 (master) and newer.
Link: https://gitlab.com/qemu-project/qemu/-/issues/964

boot-qemu.sh: Use different CPU for arm64 with new QEMU + old kernel

---

boot-qemu.sh

By default, QEMU's TCG uses the architected QARMA algorithm for pointer
authentication, which is better cryptographically but extremely slow to
emulate. As of QEMU 6.0.0, there is an "Implementation Defined"
algorithm available, which is not cryptographic but significantly faster
to run.
`ARCH=arm64 defconfig`:
```
Benchmark 1: QARMA
Time (mean ± σ):     10.381 s ±  0.048 s    [User: 8.469 s, System: 0.142 s]
Range (min … max):   10.317 s … 10.478 s    50 runs
Benchmark 2: Implementation Defined
Time (mean ± σ):      7.051 s ±  0.015 s    [User: 5.125 s, System: 0.130 s]
Range (min … max):    7.014 s …  7.083 s    50 runs
Summary
'Implementation Defined' ran
1.47 ± 0.01 times faster than 'QARMA'
```
`ARCH=arm64 defconfig` + `KASAN_SW_TAGS` + the KUnit tests:
```
Benchmark 1: QARMA
Time …
```

boot-qemu.sh: Use implementation defined pointer authentication algorithm

---

boot-uml.sh

A fix for this issue has been merged into mainline and it has been in
-next for a few days already.
Closes: https://github.com/ClangBuiltLinux/boot-utils/issues/60
Link: https://git.kernel.org/linus/57ae0b67b747031bc41fb44643aa5344ab58607e

boot-uml.sh: Remove exec hack

---

boot-qemu.sh

To make things easier for shutting down after a reboot (or a reboot on
panic), always use -no-reboot regardless of architecture.
Signed-off-by: Kees Cook <keescook@chromium.org>

boot-qemu: Always use -no-reboot

---

README.txt
boot-qemu.sh

Introduce optional "--append" argument to add an additional string to
the kernel command line.
Signed-off-by: Kees Cook <keescook@chromium.org>

boot-qemu: Introduce --append

---

boot-qemu.py

CI reported a crash when attempting to boot arm64 kernels:
```
Traceback (most recent call last):
File ".../boot-qemu.py", line 727, in <module>
cfg = get_qemu_args(cfg)
File ".../boot-qemu.py", line 451, in get_qemu_args
linux_ver_code = get_linux_ver_code(gzip_kernel_cmd)
File ".../boot-qemu.py", line 338, in get_linux_ver_code
return create_version_code(linux_version)
File ".../boot-qemu.py", line 262, in create_version_code
major, minor, patch = [int(version[i]) for i in (0, 1, 2)]
File ".../boot-qemu.py", line 262, in <listcomp>
major, minor, patch = [int(version[i]) for i in (0, 1, 2)]
ValueError: invalid literal for int() with base 10: '%s'
```
Looking at the strings output reveals:
```
$ gzip -d -c Image.gz &| strings &| grep "Linux version "
Linux version %s (%s)
Linux version …
```

boot-utils.py: Fix searching for Linux kernel version numbers

---

boot-qemu.py
utils.py

Otherwise, when running non-interactively (such as through GitHub
Actions), the output from these print statements might not appear before
QEMU's output, making it hard to decipher what has gone wrong.

boot-utils: Flush print commands to ensure output is properly ordered

---

boot-qemu.py

As pointed out by Cédric [1], POWER8 is a little old. We moved from
POWER9 to POWER8 in commit 29f7dba ("boot-qemu.sh: Specify POWER8 CPUs
for ppc64 and ppc64le") because of the rootfs, which works fine on a
POWER9 machine as well, which is the current meaning of the 'powernv'
machine. This has been tested with all the images from
continuous-integration2 to ensure it is safe for all the versions we
test.
[1]: https://github.com/ClangBuiltLinux/boot-utils/commit/a0540ceaccd97e92d2c2eb0ea504e762a174171b#r83919704

boot-qemu: Move from 'powernv8' to 'powernv' machine

---

boot-qemu.py

When CONFIG_LOCALVERSION_AUTO is not set, the Linux version string may be
"Linux version x.y.z+", which is not handled gracefully by the script:
```
Traceback (most recent call last):
File ".../boot-utils/boot-qemu.py", line 726, in <module>
cfg = get_qemu_args(cfg)
File ".../boot-utils/boot-qemu.py", line 452, in get_qemu_args
linux_ver_code = get_linux_ver_code(gzip_kernel_cmd)
File ".../boot-utils/boot-qemu.py", line 339, in get_linux_ver_code
return create_version_code(linux_version)
File ".../boot-utils/boot-qemu.py", line 263, in create_version_code
major, minor, patch = [int(version[i]) for i in (0, 1, 2)]
File ".../boot-utils/boot-qemu.py", line 263, in <listcomp>
major, minor, patch = [int(version[i]) for i in (0, 1, 2)]
ValueError: invalid literal for int() with base 10: '0+' …
```

boot-qemu.py: Fix get_linux_ver_code() when CONFIG_LOCALVERSION_AUTO is not set

---

boot-qemu.py
boot-uml.py
utils.py

The commit messages should be self explanatory but this PR updates boot-utils to use f-strings (preferred in Python 3.6+) and eliminates as_posix() calls on path objects (possible after Python 3.6+), which cleans up the code a bit.

boot-utils: Python updates

---

boot-qemu.py

Two `-machine` arguments looks odd, especially since the `gic-version`
parameter is specified on the first `-machine` instance.
Append `virtualization=true` to the existing machine string in a similar
manner to `gic-version` to keep everything uniform. Additionally, add a
comment around why and where `virtualization=true` is specified.

boot-qemu.py: Combine aarch64 machine flags

---

boot-qemu.py

There is no reason to roll our own versioning format when we can
automatically generate tuples for the versions to allow more natural and
obvious comparisons, similar to `sys.version_info`. For example:
```python
if qemu_ver_code < 602050:
```
vs.
```python
if qemu_ver < (6, 2, 50):
```

boot-qemu.py: Use tuples for Linux and QEMU versions

---

.github/workflows/main.yml
boot-qemu.py
boot-uml.py
utils.py

See the individual commits for the warnings.
Depends on https://github.com/ClangBuiltLinux/actions-workflows/pull/4.

boot-utils: Fixes for flake8 and pylint

---

boot-qemu.py
images/.gitignore
utils.py

Booting under UEFI can expose potential issues that will impact real
hardware, like CFI failures. Add support for booting under UEFI with
arm64 and x86_64 by searching for firmare on the user's system, copying
and modifying it as necessary, then passing it along to QEMU.
This is deliberately a separate option that is off by default, as I am
not sure we can turn this on by default without regressing older trees
or toolchains. It has only been tested with tip of tree Linux and LLVM.
Closes: https://github.com/ClangBuiltLinux/boot-utils/issues/14

boot-qemu.py: Add support for booting arm64 and x86_64 guests under UEFI

---

boot-qemu.py

There is a typo in the original message (missing "un" on "supported").
Take the opportunity to make the message a little more consise.

boot-qemu.py: Update unsupported EFI boot message

---

boot-qemu.py

The existing check for `/dev/kvm` is not strong enough, as it is
possible that `/dev/kvm` exists but the user does not have sufficient
permissions to access it, which will result in QEMU immediately refusing
to start. This can be quite frustrating when doing a sequence of builds
non-interactively, as the results will be tainted due to the initial
startup failure.
Switch to `os.access()`, which allows us to make sure `/dev/kvm` is
writeable with the current permissions.
At the same time, clean up this function. If `/dev/kvm` is accessible,
it implies hardware virtualization support, so we can ditch the
`/proc/cpuinfo` check for x86. Refactor the 32-bit EL1 check for aarch64
to its own function, which allows us to compact the aarch64 section
signficantly.

boot-qemu.py: Simplify can_use_kvm()

---

boot-qemu.py

Otherwise, the call to `sys.exit()` in `die()` does not work and we end up
hanging.
Additionally, move it out of the while loop, as it does not make send to
check for `gdb_bin` every single time we want to invoke it.

boot-qemu.py: Check gdb_bin earlier

---

boot-qemu.py

Detach QEMU from the process group so that SIGINT isn't also delivered to it.
Ignore SIGINT in python when running GDB subprocess.
Link: https://stackoverflow.com/a/13737455
Link: https://stackoverflow.com/q/30925198
Fixes: https://github.com/ClangBuiltLinux/boot-utils/issues/86

boot-qemu.py: fix ctrl+c in gdb

---

boot-qemu.py

A couple of fixes for new pylint. See each change for the full warning and details.

boot-utils: Fix new pylint warnings

---

boot-qemu.py

This effectively reverts commit 8c78e38 ("boot-qemu: Always use
-no-reboot") against the rewrite that occurred in #91.
By applying this unconditionally, we potentially miss out on catching
panics. Prior to that change, if a machine panicked and rebooted, it
would keep rebooting until timeout killed QEMU, resulting in a non-zero
exit code. After that change, QEMU just exits cleanly on reboot.
cc @kees, I cannot remember what the original reason for unconditionally adding
`-no-reboot` was.

boot-qemu.py: Do not add '-no-reboot' unconditionally

---

boot-qemu.py

We can run `file` on vmlinux (if it is available) to try and guess what
kernel we are booting. Certain architectures are ambiguous so we just
require the user to provide `-a` for those.
Closes: https://github.com/ClangBuiltLinux/boot-utils/issues/48

boot-qemu.py: Attempt to guess architecture from vmlinux without '-a'

---

ruff.toml

Reading the bandit documentation, these warnings are low severity and
it would make the code significantly worse to try and work around them,
so opt out of them. These calls are working as intended and this script
is designed to be used interactively so injection is not a concern.
Link: https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html
Link: https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

ruff.toml: Disable S603 and S607

---

boot-qemu.py

Closes: https://github.com/ClangBuiltLinux/boot-utils/issues/98

boot-qemu.py: Add file strings for aarch64 with CONFIG_RELOCATABLE=n

---

boot-qemu.py

This is needed to automatically boot `ppc64_guest_defconfig` +
`CONFIG_PPC64_BIG_ENDIAN_ELF_ABI_V2=y`.
Add both the pie and non-pie variants, even though it is unlikely that
`CONFIG_RELOCATABLE` will be disabled, as it is selected by a few
different options in the defconfigs that this script will typically be
booting, but it does not hurt to be proactive.

boot-qemu.py: Add ppc64 big endian ELFv2 file strings to file_rosetta

---

utils.py

When attempting to use `-k .` with `boot-uml.py`, the following stacktrace
is observed:
```
$ .../boot-uml.py -k .
$ linux ubd0=.../boot-utils/images/x86_64/rootfs.ext4
Traceback (most recent call last):
File ".../boot-utils/boot-uml.py", line 82, in <module>
run_kernel(kernel, decomp_rootfs(), args.interactive)
File ".../boot-utils/boot-uml.py", line 75, in run_kernel
subprocess.run(uml_cmd, check=True)
File "/usr/lib/python3.11/subprocess.py", line 548, in run
with Popen(*popenargs, **kwargs) as process:
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib/python3.11/subprocess.py", line 1917, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename) …
```

utils: Expand relative paths in get_full_kernel_path()

---

boot-qemu.py

A refactoring commit adjusted the structure of the dts folder in
`arch/arm` to match `arch/arm64` (vendor sub-directories).
Adjust the `_dtb` member of `QEMURunner` to be a list of potential locations
for the dtbs, so that they can be found before and after this move,
which works for all kernel versions that this script supports.
Link: https://git.kernel.org/next/linux-next/c/724ba6751532055db75992fc6ae21c3e322e94a7

boot-qemu.py: Handle dtb location shuffle in linux-next

---

boot-qemu.py

Ensure `images/loongarch` exists before trying to download the firmware.
I missed this because `images/loongarch` was erroneously a part of the
history when LoongArch support was merged in #109.

boot-qemu.py: Fix downloading LoongArch firmware

---

boot-qemu.py

This is the same warning from `pylint` that was disabled in https://github.com/ClangBuiltLinux/actions-workflows/pull/5.
```
boot-qemu.py:216:35: PLW1509 `preexec_fn` argument is unsafe when using threads
```
`preexec_fn` is on the path towards deprecation, so workaround this warning by refactoring the code to use the new keyword argument `process_group` when using Python 3.11 and newer, which makes it clear that we don't need `preexec_fn` longterm. This conveniently hides the `preexec_fn` use in `Popen()` so there is no more warning.
Link: https://beta.ruff.rs/docs/rules/subprocess-popen-preexec-fn/

boot-qemu.py: Workaround PLW1509 warning from Ruff

---

utils.py

Occasionally, I have noticed the occasional failure to query GitHub's
rate limit API for various reasons, even when providing an up to date
release JSON file via '--gh-json-file'. A rate limit query is unneeded
in this instance because we are not going to query GitHub's API for the
latest release information, as it has already been provided to us by the
user.
Restructure the code so that the rate limit API is only queried when we
will actually need to query the API for the latest release.

utils.py: Do not query GitHub's API at all with '--gh-json-file'

---

boot-qemu.py

The default memory value for most machines is 512 MB, which is generally sufficient for most use cases, as these machines are usually quick to start up and shutdown. Unfortunately, there are times where the machine may run out of memory when percpu memory allocations are involved along with a large number of cores, which can happen when booting under KVM due to the script's heuristics for selecting a good default for `-smp`, which depends on the number of cores on the host machine.
Rather than try to adjust the existing heuristics further, allow users to specify a memory value that may be better suited for their machine, just like `-smp`.

boot-qemu.py: Allow memory value to be customized

---

boot-qemu.py

This has been broken for an embarrassingly long time...
Fixes: 09a59ca ("boot-qemu.py: Do not make gdb imply interactive")

boot-qemu.py: Fix GDB check in QEMURunner

---

ruff.toml

There is a deprecation warning for top level lint settings:
```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `ruff.toml`:
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
```
Move these under the lint section. Additionally, update the link to the rules.

ruff.toml: Update for 0.2.0

---

boot-qemu.py

arm kernels can be booted via EFI in the same manner as arm64. Refactor the current EFI image creation logic into its own class so that `arm32_v7` and `arm64` can share most of the logic, just with different files.

boot-qemu.py: Add support for booting ARCH=arm kernels via EFI

---

.github/workflows/main.yml

We should ensure our code stays compatible with the latest stable release of Python.

workflows: main: Add Python 3.12

---

boot-qemu.py
utils.py

```
boot-qemu.py:148:32: E0606: Possibly using variable 'decomp_cmd' before assignment (possibly-used-before-assignment)
utils.py:215:24: E0606: Possibly using variable 'gh_json_rel' before assignment (possibly-used-before-assignment)
```

boot-utils: Address new pylint possibly-used-before-assignment warnings

---

boot-qemu.py

Loongson renamed this file in https://github.com/loongson/Firmware/commit/638906de6143283d86c70d80f4e9a30b50731c24, which results in a 404 file getting downloaded as the firmware, so QEMU obviously refuses to start. If the old firmware file does not exist locally already, download and use the new file name.

boot-qemu.py: Handle LoongArch's EFI firmware location change

---

boot-qemu.py

If the old firmware filename does not exist, the new firmware is always downloaded, even if it already exists. Remove the handling for the old to new transition so that the firmware is only downloaded when it is actually needed.

boot-qemu.py: Fix always downloading LoongArch firmware
